// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yojdovitafdqllacnvuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvamRvdml0YWZkcWxsYWNudnVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5NTI3MDgsImV4cCI6MjA4NjUyODcwOH0.B2iaeb0awFfDZ-w8Ev6btKXedCjQw9-DqepSULDZgiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});