// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxpvdbsecrvonniurcbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4cHZkYnNlY3J2b25uaXVyY2JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4NTM1NjQsImV4cCI6MjA4NzQyOTU2NH0.0CVUqbx_uC_KGaXmUekenQNnrTTGpoPDYj2MpBvd8bo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});